"""Public helpers for building and running doc2tei configurations."""

from .config import Rule, rule, rule_group
from .extractors import (
    CharacterPDFExtractor,
    LineRecord,
    PageRange,
    RunRecord,
    WordPDFExtractor,
)
from .helpers import (
    FootnoteLinker,
    SpeakerUtteranceHook,
    build_list_person,
    build_tei_corpus,
    merge_speaker_mappings,
)
from .parser import (
    LoadedConfig,
    ParseDiagnostics,
    ParseResult,
    load_config,
    parse_document,
)
from .batch import (
    BatchItemResult,
    BatchJob,
    BatchOptions,
    automatic_document_workers,
    batch_counts,
    discover_batch_jobs,
    document_list_person_path,
    document_path,
    metadata_dir,
    run_batch,
    write_batch_corpus_outputs,
    write_batch_list_person_outputs,
)
from .sistory import (
    SIstoryDownloadResult,
    download_sistory_menu,
    normalize_sistory_menu_path,
)
from .selectors import AllOf, AnyOf, Attribute, Between, LineStart, Metadata, Not, Text
from .tei_header import (
    Change,
    Funder,
    Measure,
    Meeting,
    Person,
    RespStmt,
    Setting,
    SourceBibl,
    TEIHeader,
    fill_counts,
)

__all__ = [
    "AllOf",
    "AnyOf",
    "Attribute",
    "Between",
    "BatchItemResult",
    "BatchJob",
    "BatchOptions",
    "Change",
    "CharacterPDFExtractor",
    "Funder",
    "FootnoteLinker",
    "LineRecord",
    "LineStart",
    "LoadedConfig",
    "Measure",
    "Meeting",
    "Metadata",
    "Not",
    "PageRange",
    "ParseDiagnostics",
    "ParseResult",
    "Person",
    "RespStmt",
    "Rule",
    "RunRecord",
    "Setting",
    "SourceBibl",
    "SpeakerUtteranceHook",
    "SIstoryDownloadResult",
    "TEIHeader",
    "Text",
    "WordPDFExtractor",
    "build_list_person",
    "build_tei_corpus",
    "merge_speaker_mappings",
    "automatic_document_workers",
    "batch_counts",
    "discover_batch_jobs",
    "document_list_person_path",
    "document_path",
    "download_sistory_menu",
    "fill_counts",
    "metadata_dir",
    "load_config",
    "parse_document",
    "normalize_sistory_menu_path",
    "rule",
    "rule_group",
    "run_batch",
    "write_batch_corpus_outputs",
    "write_batch_list_person_outputs",
]
